Feature/status command
NodeFactoryIo/hactar-daemon pull request #43
Opened 2020-03-05 19:17 UTC by MakMuftic

Closes #19 

I also refactored commands code in this PR so each command is in a separate file.

2020-03-05 21:28 UTC, morrigan requested changes
Looks great! Thanks for adding the timestamp info, it inspired me for something more :D

2020-03-05 21:28 UTC, morrigan commented on cmd/hactar/commands/status.go
> +		fmt.Println("Unable to initialize lotus client")    // show to user
detect* This sound like we are starting one and might be confusing to our dummy users

2020-03-05 21:28 UTC, morrigan commented on cmd/hactar/commands/status.go
> +		fmt.Println("Lotus worker down")    // show to user
Also be more precise "miner worker*"

2020-03-05 21:28 UTC, morrigan commented on cmd/hactar/commands/status.go
> +		"Last reported tipset of height %d at %s",
You can put something like "Monitoring block rewards, last reported tipset is..."

2020-03-05 21:28 UTC, morrigan commented on cmd/hactar/commands/status.go
> +
Add another message "Reporting other stats on the following intervals:" and display the intervals

2020-03-06 12:09 UTC, MakMuftic commented
@morrigan this is sample output of status command

```
Hactar daemon app stats
-----------------------
Actor address:  t0101
Node url:       192.168.0.32
Owner address:  t3ue7o3jzopnzh2rfivxywbqn7xc3i34ng7sepmn2btfh4scod4a2ebu3oiyhhwnlpqd2noxdasozwyh2wbjea

Monitoring block rewards
------------------------
Last reported tipset height:  0
Last tipset reported at:      2020-02-03 12:20:32      

Reporting stats on the following intervals (seconds):
-----------------------------------------------------
General info report  60
Uptime report        10
Block reward report  50
Balance report       150

```

2020-03-07 17:53 UTC, morrigan approved these changes
Looks good!

FYI: UX would be better if you would read naturally "60 seconds" and not just the numbers listed :)

2020-03-07 17:53 UTC, merged